### PR TITLE
Patch 17 - New API Calls

### PR DESCRIPTION
**Pull request by asharptlm**
createOneTag and getAvailableTagTypes

### CODE REVIEW

**Comment by gcarncross** [comment]
This looks otherwise ok.

**Comment by asharptlm** [comment]
It is documented as K:K simply because that's what is live. There was no real reason for it, so could easily be changed to K:1 or an array of unique names; can change the docs to match once the change is live?

**Comment by gcarncross** [comment]
We can't *change* interfaces. Once published they cannot change and must always be supported.

**Comment by gcarncross** [comment]
If you don't want to change it, state in the documentation that the value doesn't matter and might change so don't depend on it matching the key.

**Comment by asharptlm** [comment]
Code was updated, so docs have been changed to reflect the k:v mapping instead.

**Pull request merged**
