### PR TITLE
Creative params.

### PR DESCRIPTION
**Pull request by danielmorse**

### CODE REVIEW

**Comment by gcarncross** [comment]
You sure this is what you want? Detecting encoding errors will be impossible, and AS/TS ran into that a number of times between CRM and TagExporter and again with PF between CRM and TGImporter. Seems like it would be a good idea to require a ? or a & in there so you can tell it's encoded correctly.

**Comment by danielmorse** [comment]
OK, add the '?'. Makes sense. I just now need to put more intelligence into the staging area code if we ever want add other query string variables there.

**Comment by gcarncross** [comment]
What do you mean? Can't I put something like `?whatever=foo&bar=69` in there? It'll be in the *creative path* part so it'll be encoded correctly `%3Fwhatever%3Dfoo%26bar%3D69` in the edition path?

**Comment by danielmorse** [comment]
The code in the staging area encodes it just before putting it into the
edition path, so it should be sent up unencoded. That said, if we are
checking that the '?' is present we could make it so that it accepts both
encoded and unencoded versions at the smelter.

**Comment by gcarncross** [comment]
Sounds reasonable. ok.

**Comment by danielmorse** [comment]
To be clear, when I said unencoded I meant if I go
$_REQUEST['creative_params'] in php I will get somethign like
'?key=value&key=value'. Obviously it will be encoded in transit by virtue
of the face that it is 'application/x-www-form-urlencoded' data.

**Comment by gcarncross** [comment]
Okay, but what goes into the edition path (check CRM) is `rawurlencode($_REQUEST["creative_params"])`

**Pull request merged**
